#MONGODB INFORMATION
MONGODB_URL = "mongodb://localhost:27017"
ANALYTICS_DATABASE_NAME = "analytics_db"
ANALYTICS_COLLECTION_NAME = f"analytics_{APPNAME}"
ASSETS_DATABASE_NAME = "assets_db"
CATEGORIES_COLLECTION_NAME = f"category"
ASSETS_COLLECTION_NAME = f"assets"