#SYSTEM INFORMATION
SYSTEM_IP = "172.16.0.94"
SYSTEM_PORT = 9005

#PROJECT INFORMATION
APPNAME = "shimeji"
TITLE = "SHIMEJI ASSETS"
DESCRIPTION = "CRUD operations for SHIMEJI ASSETS to add, retrieve, delete, and update assets and categories."
VERSION = "1.0.0"
AUTHOR = "Ozi Backend"

#MONGODB INFORMATION
MONGODB_URL = "mongodb://localhost:27017"
ANALYTICS_DATABASE_NAME = "analytics_db"
ANALYTICS_COLLECTION_NAME = f"analytics_{APPNAME}"
ASSETS_DATABASE_NAME = f"{APPNAME}_assets_db"
CATEGORIES_COLLECTION_NAME = f"category"
ASSETS_COLLECTION_NAME = f"assets"

#DIRECTORIES
TEMPLATES_DIR = "templates"
STATIC_DIR = "static"
SHIMEJI_ASSETS_DIR = f"{STATIC_DIR}/Assets"
SHIMEJI_CATEGORIES_DIR = f"{STATIC_DIR}/Categories"

#FILE FORMATS
IMAGE_FORMAT = "webp"
TEMPLATE_FORMAT = "html"

#IMAGE PREFIX
IMAGE_URL_PREFIX = f"https://{SYSTEM_IP}:{SYSTEM_PORT}"